name: Build Data

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */2 * * *"

permissions:
  contents: write

jobs:
  fetch-and-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Fetch data (FRED + stooq)
        env:
          FRED_API_KEY: ${{ secrets.FRED_API_KEY }}
        run: python3 scripts/fetch_data.py

      - name: Validate output (fail if GOLD < 180)
        run: |
          test -f data/history.json && test -f data/spot.json && test -f data/diag.json
          echo "diag.json:"
          cat data/diag.json
          GOLD_VALID=$(python3 - << 'PY'
import json
j=json.load(open('data/diag.json'))
print(j.get('gold_valid',0))
PY
)
          echo "GOLD valid points: ${GOLD_VALID}"
          if [ "${GOLD_VALID}" -lt 180 ]; then
            echo "Too few GOLD data points for forecasts."; exit 1;
          fi

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A data/
          if git diff --cached --quiet; then
            echo "No changes."
          else
            git pull --rebase origin "${GITHUB_REF_NAME:-main}" || true
            git commit -m "Data update: $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
            git push origin HEAD:"${GITHUB_REF_NAME:-main}"
          fi
