name: build-data


on:
workflow_dispatch:
schedule:
- cron: '0 */2 * * *'


permissions:
contents: write


jobs:
build:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v4


- uses: actions/setup-python@v5
with:
python-version: '3.11'


- name: Install dependencies
run: |
python -m pip install --upgrade pip
pip install requests


- name: Fetch data
env:
FRED_API_KEY: ${{ secrets.FRED_API_KEY }}
run: python scripts/fetch_data.py


- name: Commit & push
run: |
git config user.name "github-actions[bot]"
git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
git add data/history.json data/spot.json || true
git commit -m "data: update $(date -u +'%Y-%m-%dT%H:%M:%SZ')" || exit 0
git push
