name: Build Data

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */2 * * *"  # alle 2 Stunden

permissions:
  contents: write

jobs:
  fetch-and-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Fetch data (FRED + stooq)
        env:
          FRED_API_KEY: ${{ secrets.FRED_API_KEY }}
        run: |
          set -e
          python3 scripts/fetch_data.py
          echo "--- head history.json ---"
          head -n 5 data/history.json || true
          echo "--- spot.json ---"
          cat data/spot.json || true
          echo "--- diag.json ---"
          cat data/diag.json || true

      # Commit zuerst, damit diag/history/spot immer im Repo landen
      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A data/
          if git diff --cached --quiet; then
            echo "No changes."
          else
            git pull --rebase origin "${GITHUB_REF_NAME:-main}" || true
            git commit -m "Data update: $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
            git push origin HEAD:"${GITHUB_REF_NAME:-main}"
          fi

      # Validate ohne Here-Doc; bricht NICHT hart ab (nur Warnung).
      # Zum Hart-Abbruch die letzte Zeile auf `exit 1` ändern.
      - name: Validate output (warn if GOLD < 180)
        run: |
          if [ ! -f data/diag.json ]; then
            echo "WARN: data/diag.json fehlt."
            exit 0
          fi
          GOLD_VALID=$(python3 -c "import json,sys; j=json.load(open('data/diag.json')); print(j.get('gold_valid',0))")
          echo "GOLD valid points: ${GOLD_VALID}"
          if [ "${GOLD_VALID}" -lt 180 ]; then
            echo "WARN: Too few GOLD data points for robust forecasts."
            # exit 1   # <- optional 'fail hard'
          fi
